@startuml
class CarsController {
    + CarsController(categoryRepository:ICategoryRepository, carRepository:ICarRepository)
    + List(category:string) : ViewResult
}
Controller <|-- CarsController
@enduml
